owner: KachanovTeam
repo: status

sites:
  - name: '[Сервер] Лобби'
    check: "tcp-ping"
    url: $LOBBY_SERVER_KT
    port: 9999
  - name: '[Сервер] Выживание'
    check: "tcp-ping"
    url: $SURVIVAL_SERVER_KT
    port: 25554

assignees:
- Juliano Medichi
- sepera-okeq

status-website:
  cname: status.kachanovcraft.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "**KachanovTeam Status Servises**"
  introMessage: Здесь вы можете получить информацию о состоянии серверов и сервисов, подконтрольные KachanovTeam. <br> Пожалуйста, отслеживайте данную страницу на факт наличия проблем, все проблемы будут опубликованы здесь.
  navbar:
    - title: Статус
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

i18n:
  footer: 'Страница отслеживания состояния сервисов KachanovCraft. <br> KachanovTeam © 2022. Создано при помощи [Upptime](https://upptime.js.org).'
  allSystemsOperational: 'Все системы работают!'
