owner: KachanovTeam
repo: status

sites:
  - name: '[Сервер] Лобби'
    url: https://www.google.com
  - name: '[Сервер] Выживание'
    url: https://en.wikipedia.org
  - name: '[Сервер] Выживание **(DEV)**'
    url: https://news.ycombinator.com

assignees:
- Juliano Medichi
- sepera-okeq

status-website:
  cname: status.kachanovcraft.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status
  introTitle: "**KachanovCraft** это комплекс серверов, которые дают новые возможности."
  introMessage: Здесь вы можете получить информацию о состоянии серверов и сервисов, подконтрольные KachanovTeam. Пожалуйста, отслеживайте данную страницу на факт наличия проблем, все проблемы будут опубликованы здесь.
  navbar:
    - title: Статус
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark

i18n:
  footer: 'Страница отслеживания состояния сервисов KachanovCraft. KachanovTeam © 2022. Создано при помощи [Upptime](https://upptime.js.org)'.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
